- name: play level variables
  hosts: local
  connection: local
  vars: # This is Global access
    COURSE: DevOps with AWS
    DURATION: 10HR
    STUDENT: Prudhvi Sai
  tasks:
  - name: print course information
    vars: # This is local access
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration is {{ DURATION }}, Student is {{ STUDENT }}"

  - name: print course information again
    ansible.builtin.debug:
    # vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course duration is {{ DURATION }}, Student is {{ STUDENT }}"