- name: ping the server
  hosts: keys
  become: yes
  tasks: # list of tasks
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes